# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

erfcx <- function(z_, relerr = 0) {
    .Call('RcppFaddeeva_erfcx', PACKAGE = 'RcppFaddeeva', z_, relerr)
}

erf <- function(z_, relerr = 0) {
    .Call('RcppFaddeeva_erf', PACKAGE = 'RcppFaddeeva', z_, relerr)
}

erfi <- function(z_, relerr = 0) {
    .Call('RcppFaddeeva_erfi', PACKAGE = 'RcppFaddeeva', z_, relerr)
}

erfc <- function(z_, relerr = 0) {
    .Call('RcppFaddeeva_erfc', PACKAGE = 'RcppFaddeeva', z_, relerr)
}

Dawson <- function(z_, relerr = 0) {
    .Call('RcppFaddeeva_Dawson', PACKAGE = 'RcppFaddeeva', z_, relerr)
}

Faddeeva_w <- function(z_, relerr = 0) {
    .Call('RcppFaddeeva_Faddeeva_w', PACKAGE = 'RcppFaddeeva', z_, relerr)
}

