# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute erfcx(z) = exp(z^2) erfc(z)
#'
#' @param z complex vector
#' @param relerr double, requested error
#' @return complex vector
#' @describeIn wrap
#' @family wrapper
#' @examples 
#' erfcx(1:10 + 1i)
#' @export
erfcx <- function(z, relerr = 0) {
    .Call('RcppFaddeeva_erfcx', PACKAGE = 'RcppFaddeeva', z, relerr)
}

#' compute erf(z), the error function of complex arguments
#'
#' @param z complex vector
#' @param relerr double, requested error
#' @return complex vector
#' @describeIn wrap
#' @family wrapper
#' @examples 
#' erf(1:10 + 1i)
#' @export
erf <- function(z, relerr = 0) {
    .Call('RcppFaddeeva_erf', PACKAGE = 'RcppFaddeeva', z, relerr)
}

#' compute erfi(z) = -i erf(iz), the imaginary error function
#'
#' @param z complex vector
#' @param relerr double, requested error
#' @return complex vector
#' @describeIn wrap
#' @family wrapper
#' @examples 
#' erfi(1:10 + 1i)
#' @export
erfi <- function(z, relerr = 0) {
    .Call('RcppFaddeeva_erfi', PACKAGE = 'RcppFaddeeva', z, relerr)
}

#' compute erfc(z) = 1 - erf(z), the complementary error function
#'
#' @param z complex vector
#' @param relerr double, requested error
#' @return complex vector
#' @describeIn wrap
#' @family wrapper
#' @examples 
#' erfc(1:10 + 1i)
#' @export
erfc <- function(z, relerr = 0) {
    .Call('RcppFaddeeva_erfc', PACKAGE = 'RcppFaddeeva', z, relerr)
}

#' compute Dawson(z) = sqrt(pi)/2  *  exp(-z^2) * erfi(z)
#'
#' @param z complex vector
#' @param relerr double, requested error
#' @return complex vector
#' @describeIn wrap
#' @family wrapper
#' @examples 
#' Dawson(1:10 + 1i)
#' @export
Dawson <- function(z, relerr = 0) {
    .Call('RcppFaddeeva_Dawson', PACKAGE = 'RcppFaddeeva', z, relerr)
}

#' compute w(z) = exp(-z^2) erfc(-iz) (Faddeeva function)
#'
#' @param z complex vector
#' @param relerr double, requested error
#' @return complex vector
#' @describeIn wrap
#' @family wrapper
#' @examples 
#' Faddeeva_w(1:10 + 1i)
#' @export
Faddeeva_w <- function(z, relerr = 0) {
    .Call('RcppFaddeeva_Faddeeva_w', PACKAGE = 'RcppFaddeeva', z, relerr)
}

